### ISSUE TITLE
heliopy dependency is deprecated

### ISSUE THREAD

**Issue by scottshambaugh** [cmoestl/heliocats#7]
heliopy 1.0.0 [is no longer maintained](https://github.com/heliopython/heliopy), and the developers recommend switching to [astrospice ](https://astrospice.readthedocs.io/en/latest/)for reading spice data. I haven't done a full audit, but it's used at least in `icme_rate.*`.

**Comment by cmoestl** [comment]
Dear Scott, we are in the process of switching to astrospice. Thanks for the heads up!
