### ISSUE TITLE
How can we get more fresh up-to-date data?

### ISSUE THREAD

**Issue by eabase** [cmoestl/heliocats#8]
I was trying this, but the data provided by the URL is outdated by several months. 
Where can we get the latest data?

https://helioforecast.space/static/sync/icmecat/HELIO4CAST_ICMECAT_v22.csv

**Comment by cmoestl** [comment]
This file is the latest version of the ICMECAT, the last event is included from March 2024, the last update was done on April 11. We are doing updates about every 2 months and present them at https://helioforecast.space/icmecat
